env:
  browser: true
  es6: true
  webextensions: true
plugins:
  - import
  - json
  - '@typescript-eslint'
extends:
  - eslint:recommended
  - 'plugin:@typescript-eslint/recommended'
  # TODO - 'plugin:@typescript-eslint/strict'
  - 'plugin:@typescript-eslint/stylistic'
  #- plugin:json/recommended
  - plugin:import/recommended
  - plugin:import/typescript
parserOptions:
  sourceType: module
  ecmaVersion: 2018
rules:

  # Style
  indent:
    - warn
    - 4
    - SwitchCase: 1
  linebreak-style:
    - error
    - unix
  semi:
    - error
    - always
  no-var: error
  no-sequences: error

  '@typescript-eslint/no-unused-vars': [error, {argsIgnorePattern: "^_"}]

  # Additional control
  import/no-cycle: error
  import/first: error
  # Would be nice to enforce order, but after resolution they are all relative
  #import/order:
  #  - warn
  #  - newlines-between: never

  "json/*": [error, allowComments]
settings:
  import/resolver:
    typescript: true
