#include "nsISupports.idl"
interface nsIBriefFeed;
interface nsIVariant;

/**
 * nsIBriefUpdateService is responsible for downloading and parsing feeds. It
 * interacts with nsIBriefStorage service to update the database with the obtained data.
 */
[scriptable, uuid(76607B92-7E83-11DB-9369-10F955D89593)]
interface nsIBriefUpdateService : nsISupports {

  /**
   * Indicates if updating is in progress.
   */
  const short NOT_UPDATING = 0;
  const short BACKGROUND_UPDATING = 1;
  const short NORMAL_UPDATING = 2;

  readonly attribute short status;

  /**
   * Total number of feeds scheduled for current batch update (both completed
   * and pending ones).
   */
  readonly attribute unsigned long scheduledFeedsCount;

  /**
   * Number of completed feed in the current batch update.
   */
  readonly attribute unsigned long completedFeedsCount;

  /**
   * Download feeds and check them for updates. They must already be in the
   * database.
   *
   * @param feeds         Array of nsIBriefFeed's to be updated.
   * @param inBackground  Fetch feeds with longer delay, designed for updating in the
   *                      background.
   */
  void fetchFeeds(in nsIVariant feeds, in boolean inBackground);

  /**
   * Download and check for updates all the feeds in the database.
   *
   * @param inBackground  Fetch feeds with longer delay, designed for updating in the
   *                      background.
   */
  void fetchAllFeeds(in boolean inBackground);

  void stopFetching();

};
